package Vista;

import Controlador.Ctrl_Clientes;
import Controlador.Ctrl_Oracle;
import Modelo.Clientes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class FramePrincipal extends javax.swing.JFrame {

    public static Ctrl_Oracle co;
    public static Ctrl_Clientes cc;
    public static Clientes c;
        
    public FramePrincipal() {       
        try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        } catch(Exception ignored) {}
        initComponents();
        setLocationRelativeTo(null);
        
        co = new Ctrl_Oracle();
        
        if (co.conectarBD("@localhost", "1521", "CLIENTES", "CLIENTES")) {
        } else {
            JOptionPane.showMessageDialog(null, "Conexión fallida", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }
    
    public void limpiarTxt() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPrimerApellido.setText("");
        txtSegundoApellido.setText("");
        txtTelefono.setText("");
        txtFechaNacimiento.setText("");
        txtDireccion.setText("");
        txtSegundoApellido.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCodCliente = new javax.swing.JDialog();
        btnAceptarModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCodClienteModificar = new javax.swing.JTextField();
        btnCancelarModificar = new javax.swing.JButton();
        dlgBuscar = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        cmbFiltrarPor = new javax.swing.JComboBox<>();
        txtParametroABuscar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnAceptarBusqueda = new javax.swing.JButton();
        btnCancelarBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnAnadirCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        btnEliminarBusqueda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniCargar = new javax.swing.JMenuItem();
        mniDesconectar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniLimpiarTabla = new javax.swing.JMenuItem();

        dlgCodCliente.setTitle("Modificar");
        dlgCodCliente.setAlwaysOnTop(true);
        dlgCodCliente.setMinimumSize(new java.awt.Dimension(234, 136));
        dlgCodCliente.setResizable(false);
        dlgCodCliente.setSize(new java.awt.Dimension(234, 96));

        btnAceptarModificar.setText("Aceptar");
        btnAceptarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarModificarActionPerformed(evt);
            }
        });

        jLabel8.setText("Código del cliente que deseas modificar");

        btnCancelarModificar.setText("Cancelar");
        btnCancelarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCodClienteLayout = new javax.swing.GroupLayout(dlgCodCliente.getContentPane());
        dlgCodCliente.getContentPane().setLayout(dlgCodClienteLayout);
        dlgCodClienteLayout.setHorizontalGroup(
            dlgCodClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCodClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCodClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodClienteModificar)
                    .addGroup(dlgCodClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dlgCodClienteLayout.createSequentialGroup()
                        .addComponent(btnAceptarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dlgCodClienteLayout.setVerticalGroup(
            dlgCodClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgCodClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgCodClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarModificar)
                    .addComponent(btnCancelarModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgBuscar.setTitle("Buscar");
        dlgBuscar.setMinimumSize(new java.awt.Dimension(256, 200));
        dlgBuscar.setResizable(false);
        dlgBuscar.setSize(new java.awt.Dimension(256, 200));

        jLabel14.setText("Insertar valor");

        cmbFiltrarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CodCliente", "Nombre", "ApellidoUno", "ApellidoDos", "Telefono", "FechaNacimiento", "Direccion"}));

        jLabel15.setText("Buscar por");

        btnAceptarBusqueda.setText("Aceptar");
        btnAceptarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarBusquedaActionPerformed(evt);
            }
        });

        btnCancelarBusqueda.setText("Cancelar");
        btnCancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgBuscarLayout = new javax.swing.GroupLayout(dlgBuscar.getContentPane());
        dlgBuscar.getContentPane().setLayout(dlgBuscarLayout);
        dlgBuscarLayout.setHorizontalGroup(
            dlgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtParametroABuscar)
                    .addComponent(cmbFiltrarPor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBuscarLayout.createSequentialGroup()
                        .addComponent(btnAceptarBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgBuscarLayout.createSequentialGroup()
                        .addGroup(dlgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dlgBuscarLayout.setVerticalGroup(
            dlgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtParametroABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFiltrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dlgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgBuscarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnAceptarBusqueda))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBuscarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarBusqueda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de base de datos de José Carlos López");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Nombre", "Primer apellido", "Segundo apellido", "Teléfono", "Nacimiento", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setResizable(false);
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblClientes.getColumnModel().getColumn(1).setResizable(false);
            tblClientes.getColumnModel().getColumn(2).setResizable(false);
            tblClientes.getColumnModel().getColumn(3).setResizable(false);
            tblClientes.getColumnModel().getColumn(4).setResizable(false);
            tblClientes.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblClientes.getColumnModel().getColumn(5).setResizable(false);
            tblClientes.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblClientes.getColumnModel().getColumn(6).setResizable(false);
            tblClientes.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(273, 478));
        jPanel1.setMinimumSize(new java.awt.Dimension(273, 478));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(273, 478));

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer apellido");

        jLabel4.setText("Segundo apellido");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setText("Dirección");

        btnAnadirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAnadirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirClienteClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo)
                    .addComponent(txtNombre)
                    .addComponent(txtPrimerApellido)
                    .addComponent(txtSegundoApellido)
                    .addComponent(txtTelefono)
                    .addComponent(txtFechaNacimiento)
                    .addComponent(txtDireccion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAnadirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addGap(15, 15, 15)
                                .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)))
                        .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loupe.png"))); // NOI18N
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnEliminarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        btnEliminarBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBusquedaActionPerformed(evt);
            }
        });

        jMenu1.setText("Conexión");

        mniCargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mniCargar.setText("Cargar datos de la base de datos");
        mniCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCargarActionPerformed(evt);
            }
        });
        jMenu1.add(mniCargar);

        mniDesconectar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mniDesconectar.setText("Desconectar de la base de datos");
        mniDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDesconectarActionPerformed(evt);
            }
        });
        jMenu1.add(mniDesconectar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tabla");

        mniLimpiarTabla.setText("Limpiar tabla");
        mniLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLimpiarTablaActionPerformed(evt);
            }
        });
        jMenu2.add(mniLimpiarTabla);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void actualizarLista() {
        DefaultTableModel model = (DefaultTableModel)tblClientes.getModel();
        Controlador.Ctrl_Clientes cc = new Ctrl_Clientes();
        
        ArrayList<Clientes> listaC = cc.listarClientes();        
        
        for (Clientes c : listaC) {
            model.addRow(new Object[] {
                c.getCodCliente(),
                c.getNombre(),
                c.getApellidoUno(),
                c.getApellidoDos(),
                c.getTelefono(),
                c.getFechaNacimiento(),
                c.getDireccion()
            });
        }
    }
    
    private void mniCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCargarActionPerformed
        limpiarTabla();
        actualizarLista();
    }//GEN-LAST:event_mniCargarActionPerformed

    private void mniDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDesconectarActionPerformed
        co.cerrarConexion();
        limpiarTabla();
    }//GEN-LAST:event_mniDesconectarActionPerformed

    private void btnAnadirClienteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirClienteClienteActionPerformed
        Controlador.Ctrl_Clientes cc = new Ctrl_Clientes();
        
        String codCliente = txtCodigo.getText();
        String nombre = txtNombre.getText();        
        String apellidoUno = txtPrimerApellido.getText();
        String apellidoDos = txtSegundoApellido.getText();
        String telefono = txtTelefono.getText();
        String fechaNacimiento = txtFechaNacimiento.getText();
        String direccion = txtDireccion.getText();
        
        if (cc.anadirCliente(codCliente, nombre, apellidoUno, apellidoDos, telefono, fechaNacimiento, direccion) <= 0) {
            JOptionPane.showMessageDialog(null, "No se pudo insertar el cliente. Recuerda que el formato de la fecha es dd/mm/yyyy y que no puede haber dos registros con el mismo código.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            limpiarTxt();
            limpiarTabla();
            actualizarLista();
        }
    }//GEN-LAST:event_btnAnadirClienteClienteActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        DefaultTableModel model = (DefaultTableModel)tblClientes.getModel();
        int indiceColumnaSeleccionada = tblClientes.getSelectedRow();
        
        txtCodigo.setText(model.getValueAt(indiceColumnaSeleccionada, 0).toString());
        txtNombre.setText(model.getValueAt(indiceColumnaSeleccionada, 1).toString());
        txtSegundoApellido.setText(model.getValueAt(indiceColumnaSeleccionada, 2).toString());
        txtPrimerApellido.setText(model.getValueAt(indiceColumnaSeleccionada, 3).toString());
        txtTelefono.setText(model.getValueAt(indiceColumnaSeleccionada, 4).toString());
        txtFechaNacimiento.setText(model.getValueAt(indiceColumnaSeleccionada, 5).toString());
        txtDireccion.setText(model.getValueAt(indiceColumnaSeleccionada, 6).toString());
    }//GEN-LAST:event_tblClientesMouseClicked

    private void mniLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLimpiarTablaActionPerformed
        limpiarTabla();
    }//GEN-LAST:event_mniLimpiarTablaActionPerformed

    private void btnAceptarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarModificarActionPerformed
        dlgCodCliente.setVisible(false);
        
        Controlador.Ctrl_Clientes cc = new Ctrl_Clientes();
        String parametro = txtCodClienteModificar.getText();
        txtCodClienteModificar.setText("");
        
        String nombre = txtNombre.getText();        
        String apellidoUno = txtPrimerApellido.getText();
        String apellidoDos = txtSegundoApellido.getText();
        String telefono = txtTelefono.getText();
        String fechaNacimiento = txtFechaNacimiento.getText();
        String direccion = txtDireccion.getText();
                
        if (cc.modificarCliente(nombre, apellidoUno, apellidoDos, telefono, fechaNacimiento, direccion, parametro) <= 0) JOptionPane.showMessageDialog(null, "No se pudo modificar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            limpiarTxt();
            limpiarTabla();
            actualizarLista();
            JOptionPane.showMessageDialog(null, "Cliente modificado.");
        }
    }//GEN-LAST:event_btnAceptarModificarActionPerformed

    private void btnCancelarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificarActionPerformed
        dlgCodCliente.setVisible(false);
        txtCodClienteModificar.setText("");
    }//GEN-LAST:event_btnCancelarModificarActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        Clientes cliente = new Clientes();
        Controlador.Ctrl_Clientes cc = new Ctrl_Clientes();
        
        String codCliente = txtCodigo.getText();
        
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres eliminar el registro?", "", JOptionPane.YES_NO_OPTION);
        if (opcion == 0) { 
            if (cc.eliminarCliente(codCliente) <= 0) JOptionPane.showMessageDialog(null, "No se pudo eliminar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            else {
                JOptionPane.showMessageDialog(null, "Cliente eliminado."); 
                limpiarTxt();
                limpiarTabla();
                actualizarLista();
            }
        } else limpiarTxt();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnAceptarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarBusquedaActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblClientes.getModel();
        Controlador.Ctrl_Clientes cc = new Ctrl_Clientes();
        
        String opcionCmb = (String) cmbFiltrarPor.getSelectedItem(); 
        String parametro = txtParametroABuscar.getText();
        
        ArrayList<Clientes> listaC = cc.listaClientes;        
                
        if (cc.buscarCliente(opcionCmb, parametro) <= 0) JOptionPane.showMessageDialog(null, "No se encontraron clientes con el parámetro indicado.", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            limpiarTabla();
            
            for (Clientes c : listaC) {
                model.addRow(new Object[] {
                    c.getCodCliente(),
                    c.getNombre(),
                    c.getApellidoUno(),
                    c.getApellidoDos(),
                    c.getTelefono(),
                    c.getFechaNacimiento(),
                    c.getDireccion()
                });
            }
            dlgBuscar.setVisible(false);
            txtParametroABuscar.setText("");
        }
    }//GEN-LAST:event_btnAceptarBusquedaActionPerformed

    private void btnCancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusquedaActionPerformed
        dlgBuscar.setVisible(false);
        txtParametroABuscar.setText("");
    }//GEN-LAST:event_btnCancelarBusquedaActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        dlgCodCliente.setDefaultCloseOperation(dlgCodCliente.DISPOSE_ON_CLOSE);
        dlgCodCliente.pack();
        dlgCodCliente.setLocationRelativeTo(null);
        dlgCodCliente.setVisible(true);
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        dlgBuscar.setDefaultCloseOperation(dlgCodCliente.DISPOSE_ON_CLOSE);
        dlgBuscar.pack();
        dlgBuscar.setLocationRelativeTo(null);
        dlgBuscar.setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel)tblClientes.getModel();
        model.setRowCount(0);
    }
    
    private void btnEliminarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBusquedaActionPerformed
        limpiarTabla();
        actualizarLista();
    }//GEN-LAST:event_btnEliminarBusquedaActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarBusqueda;
    private javax.swing.JButton btnAceptarModificar;
    private javax.swing.JButton btnAnadirCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelarBusqueda;
    private javax.swing.JButton btnCancelarModificar;
    private javax.swing.JButton btnEliminarBusqueda;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnModificarCliente;
    public javax.swing.JComboBox<String> cmbFiltrarPor;
    private javax.swing.JDialog dlgBuscar;
    private javax.swing.JDialog dlgCodCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mniCargar;
    private javax.swing.JMenuItem mniDesconectar;
    private javax.swing.JMenuItem mniLimpiarTabla;
    private javax.swing.JTable tblClientes;
    public javax.swing.JTextField txtCodClienteModificar;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtFechaNacimiento;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtParametroABuscar;
    public javax.swing.JTextField txtPrimerApellido;
    public javax.swing.JTextField txtSegundoApellido;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
